### ISSUE TITLE
dartdevc  error

### ISSUE THREAD

**Issue by marc1091** [lejard-h/angular_recaptcha#10]
I built  a  simple web program to test it out in angular 4. Recaptcha  worked  fine  from  Dartium.  However  when I  built with  dartdevc, I got errors.   Which  directory  does it generate  lib__angular_recaptcha.template.js and angular_recaptcha.template.dart ?

Loading angular, test/pub_serve and dart_to_js_script_rewriter transformers...
Building test2...
Building dartdevc modules...
Error compiling dartdevc module:test2|lib/lib__angular_recaptcha.template.js

[error] The return type 'void' isn't a 'bool', as defined by the method '_handle_input__'. (package:test2/angular_recaptcha.template.dart, line 56, col 12)

Please fix all errors before compiling (warnings are okay).
Build failed.

**Comment by lejard-h** [comment]
This should be fix now, sorry for the delay
