### ISSUE TITLE
_grecaptcha is null

### ISSUE THREAD

**Issue by marc1091** [lejard-h/angular_recaptcha#11]
This works  most of the time  but  many times  captcha  does not  render   because  _grecaptcha   is null  while  the page is rendering 

  @override
  void ngAfterViewInit() {
    if (_autoRender != false && _grecaptcha != null) {
      render();
    } else if ( _grecaptcha == null){
      window.alert('  _grecaptcha is null');
    }
  }

 -  Documentation says include the script as 
<script src="https://www.google.com/recaptcha/api.js?render=explicit"></script>
if we use  auto-render  why  should  the render be  explicit ?

-  if  we do  include the script  as  'explicit',  a call back  should also  need to be specified but the  documentation mentions  including the  script as above and  in  the dom use  autorender.  Documentation of  recaptcha recommends  including the script as -
<script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit"
        async defer>

**Comment by lejard-h** [comment]
Hi, in the new version (`0.0.10`), adding script tag is now unnecessary.

The official documentation is for javascript only, the javascript interop for dart does not let us set a dart callback on the window, I had to find a hack to be notify when the script is completely loaded, except if they change the way of loading the captcha, this should be definitively fix now.

Feel free to reopen if you still have the issue

**Comment by marc1091** [comment]
It  seems  to have  fixed the  problem  but  now  I  see  two  issues 

1.  I  have  signup page  and  a  login page.  Both  have  link  to each other and both are  ang. dart  pages.  Recaptcha is  only on signup page.  If I  directly  go to the signup page, recaptcha  shows  up fine. From this signup page, if I click on the login link to go to the login page and  then  again click on the signup link from the login page  to go to the signup page,  the recaptcha is  gone. If I refresh the page, it shows up again

2.  If I  bring up the signup page in  non-debug mode, app works  fine.  If  I run it in dartium debug mode,  nothing come up. Whole app stops.

**Comment by lejard-h** [comment]
Did you try to use ddc and chrome ? Dartium will be deprecated in Dart 2.0 and did you try to render the captcha manually by removing `auto-render` and using directly the `render()` function ?

**Comment by marc1091** [comment]
using render()  function works.  Thanks
