### ISSUE TITLE
Any plans making this library dart 2 compatible?

### ISSUE THREAD

**Issue by martflu** [lejard-h/angular_recaptcha#17]

**Comment by lejard-h** [comment]
Yes I just starded to update all my libraries

**Comment by martflu** [comment]
Ah I think you need to change `sdk: ">=2.0.0-dev.46.0 <2.0.0"` to `sdk: ">=2.0.0-dev.46.0 <3.0.0"` in your `pubspec.yaml`

**Comment by lejard-h** [comment]
published `0.1.3`
