### ISSUE TITLE
Need to upgrade dependency libraries to work with Angular 6

### ISSUE THREAD

**Issue by dukefirehawk** [lejard-h/angular_recaptcha#19]
Version 0.1.4 has dependency on angular_form 2 which prevents from working with Angular 6.

I have manually rebuild it with the latest libraries and it works perfectly.

dependencies:
  angular: ^6.0.1
  angular_forms: ^3.0.0
  js: ^0.6.2
  dart_browser_loader: ^0.0.6+1

**Comment by lejard-h** [comment]
Fixed in version `0.1.5`
