### ISSUE TITLE
missing parameter

### ISSUE THREAD

**Issue by marc1091** [lejard-h/angular_recaptcha#2]
Tried to use it as per the example -

<angular-recaptcha #recaptcha key=" the key  value ---  " [(ngModel)]="value"></angular-recaptcha>

This gives  error -  

Observatory listening at http://127.0.0.1:49653/
>EXCEPTION: Error: Missing required parameters: sitekey
  EXCEPTION: Error: Missing required parameters: sitekey
  STACKTRACE:
  dart:js                                                                       JsNative.callMethod
package:angular_recaptcha/angular_recaptcha.dart_js_interop_patch.dart 39:30  _render
package:angular_recaptcha/angular_recaptcha.dart 75:11                        AngularRecaptcha.render

if  i use -

   <angular-recaptcha [(ngModel)]="value" key=" ---  " auto-render></angular-recaptcha>

i get -  

Observatory listening at http://127.0.0.1:50686/
>EXCEPTION: NoSuchMethodError: The method 'render' was called on null.
Receiver: null
Tried calling: render()
  EXCEPTION: NoSuchMethodError: The method 'render' was called on null.
Receiver: null
Tried calling: render()
  STACKTRACE:
  dart:core                                                          Object.noSuchMethod
package:test/loginpart/hero_login_component.dart 47:9              HeroLoginComponent.ngOnInit

**Comment by lejard-h** [comment]
Do you have more code to show ?

In the second error, it looks like you try to call the render method by yourself, you don't need when you have `auto-render`

**Comment by lejard-h** [comment]
If you key is a variable, you need to use it like that

```html
<angular-recaptcha [key]="varKey" auto-render [(ngModel)]="value"></angular-recaptcha>
```

if not 
```html
<angular-recaptcha key="xxxxxxx-aaaaaaa-yyyyyy-zzzzzzz" auto-render [(ngModel)]="value"></angular-recaptcha>
```

**Comment by marc1091** [comment]
Yes explicit rendering was the problem.  It's working great. Thanks.
