### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by kseregal** [lejard-h/angular_recaptcha#7]
Hello.
I'm trying to run an example that is at https://github.com/lejard-h/angular_recaptcha
When I do the build an error occurs.

`[Error from Dart2JS on recaptcha|web/main.dart]:
web\packages\angular_recaptcha\angular_recaptcha.dart:33:32:
Class 'AngularRecaptcha' can't extend the type 'DefaultValueAccessor' because it is malformed.
Try correcting the malformed type annotation or removing the 'extends' clause.
class AngularRecaptcha extends DefaultValueAccessor implements AfterViewInit {
                               ^^^^^^^^^^^^^^^^^^^^
[Error from Dart2JS on recaptcha|web/main.dart]:
web\packages\angular_recaptcha\angular_recaptcha.dart:55:47:
'super' call arguments and constructor parameters do not match.
  AngularRecaptcha(this._ref, this.ngModel) : super(_ref) {
                                              ^^^^^^^^^^^
[Dart2JS on recaptcha|web/main.dart]:
`

**Comment by lejard-h** [comment]
what version are you using `angular_recaptcha`,`angular` and `dart`

**Comment by kseregal** [comment]
angular-4.0.0.
angular_recaptcha: ^0.0.7
sdk: '>=1.24.0 <2.0.0'

**Comment by lejard-h** [comment]
should be fix now in version `0.0.8`. let me know if you have problem

**Comment by kseregal** [comment]
In this form does not work:


`import 'package:angular/angular.dart';
import 'package:angular_recaptcha/angular_recaptcha.dart';

@Component(
    selector: 'app',
    template: '''
        <angular-recaptcha #recaptcha key="YOUR_KEY" [(ngModel)]="value"></angular-recaptcha>
        ''',
    directives: const [AngularRecaptcha])
class App implements OnInit {
  String value;
}`

EXCEPTION: Invalid argument(s): No provider found for NgModel.

I did so:


import 'package:angular/angular.dart';
import 'package:angular_recaptcha/angular_recaptcha.dart';
**import 'package:angular_forms/angular_forms.dart';**

@Component(
  selector: 'my-app',
  template: '''
      <angular-recaptcha key="6LdwZjAUAAAAAP0zg34KDjlvJchyq__jYX0ap4rV" [(ngModel)]="value"  auto-render></angular-recaptcha>
    ''',
  directives: const [**formDirectives**, AngularRecaptcha]

)
class AppComponent implements OnInit {
  String value;
  **void ngOnInit () {}**
}

**Comment by lejard-h** [comment]
Thanks I will update the example
